repos:
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.2
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy

  - repo: https://github.com/PyCQA/pylint
    rev: v3.2.7
    hooks:
      - id: pylint

  - repo: local
    hooks:
      - id: compile-requirements
        name: Compile requirements
        entry: python -m piptools compile requirements.in --output-file requirements.txt
        language: system
        types: [text]  # важно: чтобы не запускался на .py
        files: ^requirements\.in$  # запускается только на файле requirements.in
